export type Exercise = {
  name: string;
  sets: number;
  reps: string;
  description: string;
  images?: [string, string];
};

const IMG_BASE =
  'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises';

function exerciseImages(id: string): [string, string] {
  return [`${IMG_BASE}/${id}/0.jpg`, `${IMG_BASE}/${id}/1.jpg`];
}

export type MuscleGroup = {
  id: string;
  name: string;
  icon: string;
  coverImage: string;
  exercises: Exercise[];
};

export const muscleGroups: MuscleGroup[] = [
  {
    id: 'full-body',
    name: 'Full Body',
    icon: '🏋️',
    coverImage: `${IMG_BASE}/Barbell_Deadlift/0.jpg`,
    exercises: [
      { name: 'Deadlift', sets: 4, reps: '6-8', description: 'Lift barbell from ground to hip level with a flat back.', images: exerciseImages('Barbell_Deadlift') },
      { name: 'Clean and Press', sets: 3, reps: '6-8', description: 'Lift barbell to shoulders, then press overhead.', images: exerciseImages('Clean_and_Press') },
      { name: 'Thrusters', sets: 3, reps: '10-12', description: 'Front squat into an overhead press in one fluid motion.', images: exerciseImages('Kettlebell_Thruster') },
      { name: 'Burpees', sets: 3, reps: '12-15', description: 'Drop to a push-up, jump back up, and repeat.' },
      { name: 'Turkish Get-Up', sets: 3, reps: '5 each side', description: 'Rise from lying to standing while holding a weight overhead.', images: exerciseImages('Kettlebell_Turkish_Get-Up_Squat_style') },
      { name: 'Snatch', sets: 4, reps: '4-6', description: 'Lift barbell from ground to overhead in one explosive movement.', images: exerciseImages('Power_Snatch') },
      { name: 'Barbell Deadlift', sets: 3, reps: '8-10', description: 'Stand with feet hip-width, grip barbell and lift to hip level keeping back flat.', images: exerciseImages('Barbell_Deadlift') },
      { name: 'Barbell Sumo Deadlift', sets: 3, reps: '8-10', description: 'Deadlift with a wide stance and hands inside your knees.', images: exerciseImages('Barbell_Deadlift') },
      { name: 'Barbell Hip Thrust', sets: 3, reps: '8-12', description: 'Sit against a bench and thrust a loaded barbell upward with your hips.', images: exerciseImages('Barbell_Hip_Thrust') },
      { name: 'Sumo Deadlift Highpull', sets: 3, reps: '8-10', description: 'Sumo stance deadlift followed by an upright row to chin level.', images: exerciseImages('Kettlebell_Sumo_High_Pull') },
      { name: 'Kettlebell Swing', sets: 3, reps: '10-12', description: 'Hinge at hips and swing a kettlebell to shoulder height.', images: exerciseImages('One-Arm_Kettlebell_Swings') },
      { name: 'Dumbbell Hang Power Clean', sets: 3, reps: '8-10', description: 'From a hang position, explosively clean dumbbells to your shoulders.', images: exerciseImages('Dumbbell_Clean') },
    ],
  },
  {
    id: 'abs',
    name: 'Abs',
    icon: '🔥',
    coverImage: `${IMG_BASE}/Hanging_Leg_Raise/0.jpg`,
    exercises: [
      { name: 'Plank', sets: 3, reps: '30-60 sec', description: 'Hold a push-up position with a straight body.', images: exerciseImages('Plank') },
      { name: 'Hanging Leg Raise', sets: 3, reps: '10-15', description: 'Hang from a bar and raise legs to a 90-degree angle.', images: exerciseImages('Hanging_Leg_Raise') },
      { name: 'Weighted Crunches', sets: 3, reps: '15-20', description: 'Perform crunches while holding a weight on your chest.', images: exerciseImages('Weighted_Crunches') },
      { name: 'Russian Twist', sets: 3, reps: '20 total', description: 'Sit with legs raised and rotate torso side to side with a weight.', images: exerciseImages('Russian_Twist') },
      { name: 'Ab Wheel Rollout', sets: 3, reps: '10-12', description: 'Kneel and roll an ab wheel forward, then pull back.', images: exerciseImages('Ab_Roller') },
      { name: 'Cable Woodchopper', sets: 3, reps: '12 each side', description: 'Rotate torso diagonally while pulling a cable from high to low.', images: exerciseImages('Standing_Cable_Wood_Chop') },
      { name: 'Abdominal Twists Leg Up', sets: 3, reps: '10', description: 'Lie on your back with legs raised and twist your torso side to side.', images: exerciseImages('Russian_Twist') },
      { name: 'Dumbbell Abdominal Twist', sets: 3, reps: '10', description: 'Seated twist holding a dumbbell, rotating torso side to side with feet off the ground.', images: exerciseImages('Russian_Twist') },
      { name: 'Cable Up-Down Twist', sets: 3, reps: '12 each side', description: 'Rotate torso using a cable, twisting from low to high or high to low.', images: exerciseImages('Cable_Russian_Twists') },
      { name: 'Dumbbell Straight Arm Crunch', sets: 3, reps: '12-15', description: 'Hold a dumbbell with arms extended and crunch upward.', images: exerciseImages('Crunches') },
      { name: 'Weighted Crunch', sets: 3, reps: '15-20', description: 'Perform crunches while holding a weight plate on your chest.', images: exerciseImages('Weighted_Crunches') },
      { name: 'Weighted Crunch Reach', sets: 3, reps: '12-15', description: 'Crunch upward while reaching a weight toward the ceiling.', images: exerciseImages('Crunch_-_Hands_Overhead') },
      { name: 'Weighted Decline Sit-Up', sets: 3, reps: '10-12', description: 'Perform sit-ups on a decline bench while holding a weight.', images: exerciseImages('Decline_Crunch') },
      { name: 'Dumbbell Overhead Situp', sets: 3, reps: '10-12', description: 'Hold a dumbbell overhead and perform sit-ups.', images: exerciseImages('Crunches') },
      { name: 'Weighted Decline Overhead Situp', sets: 3, reps: '8-10', description: 'On a decline bench, hold a weight overhead and sit up.', images: exerciseImages('Decline_Crunch') },
    ],
  },
  {
    id: 'triceps',
    name: 'Triceps',
    icon: '💪',
    coverImage: `${IMG_BASE}/Dips_-_Triceps_Version/0.jpg`,
    exercises: [
      { name: 'Tricep Dips', sets: 3, reps: '8-12', description: 'Lower and raise your body on parallel bars, focusing on triceps.', images: exerciseImages('Dips_-_Triceps_Version') },
      { name: 'Triceps Rope Pushdown', sets: 3, reps: '10-15', description: 'Push a rope attachment down on a cable machine.', images: exerciseImages('Triceps_Pushdown_-_Rope_Attachment') },
      { name: 'Skull Crushers', sets: 3, reps: '8-12', description: 'Lying on a bench, lower a barbell to your forehead and extend.', images: exerciseImages('Lying_Triceps_Press') },
      { name: 'Close-Grip Bench Press', sets: 4, reps: '8-10', description: 'Bench press with hands shoulder-width apart to target triceps.', images: exerciseImages('Close-Grip_Barbell_Bench_Press') },
      { name: 'Overhead Triceps Extension', sets: 3, reps: '10-12', description: 'Hold a dumbbell overhead and lower it behind your head.', images: exerciseImages('Standing_Dumbbell_Triceps_Extension') },
      { name: 'Tricep Kickbacks', sets: 3, reps: '12-15', description: 'Bend forward and extend a dumbbell behind you.', images: exerciseImages('Tricep_Dumbbell_Kickback') },
      { name: 'Bar Triceps Pushdown', sets: 3, reps: '10-12', description: 'Push a straight bar down on a cable machine to extend the triceps.', images: exerciseImages('Triceps_Pushdown') },
      { name: 'Bar Triceps Pull Cable', sets: 3, reps: '10-12', description: 'Pull a bar attachment on a cable to extend the triceps.', images: exerciseImages('Triceps_Pushdown') },
      { name: 'Rope Triceps Pushdown', sets: 3, reps: '10-15', description: 'Push a rope attachment down and spread at the bottom.', images: exerciseImages('Triceps_Pushdown_-_Rope_Attachment') },
      { name: 'Standing Tricep Kickback', sets: 3, reps: '10-12', description: 'Stand and extend a dumbbell or cable behind you.', images: exerciseImages('Tricep_Dumbbell_Kickback') },
      { name: 'Triceps Extension Left Right', sets: 3, reps: '10-12', description: 'Single-arm triceps cable extension, alternating left and right.', images: exerciseImages('Cable_One_Arm_Tricep_Extension') },
      { name: 'Assisted Triceps Dip', sets: 3, reps: '8-12', description: 'Perform triceps dips with machine or band assistance.', images: exerciseImages('Dips_-_Triceps_Version') },
      { name: 'Dumbbell Standing French Press', sets: 3, reps: '10-12', description: 'Stand and lower a dumbbell behind your head, then extend overhead.', images: exerciseImages('Standing_Dumbbell_Triceps_Extension') },
      { name: 'Dumbbell Lying Tricep Extension', sets: 3, reps: '10-12', description: 'Lie on a bench and lower dumbbells beside your head, then extend.', images: exerciseImages('Lying_Dumbbell_Tricep_Extension') },
      { name: 'Dumbbell Floor Skullcrusher', sets: 3, reps: '10-12', description: 'Lie on the floor and lower dumbbells toward your forehead, then extend.', images: exerciseImages('EZ-Bar_Skullcrusher') },
      { name: 'Dumbbell Decline Overhead', sets: 3, reps: '10-12', description: 'On a decline bench, lower a dumbbell behind your head and extend.', images: exerciseImages('Decline_Dumbbell_Triceps_Extension') },
      { name: 'Barbell Close-Grip Chest Press', sets: 3, reps: '8-10', description: 'Press a barbell with a narrow grip to target the triceps.', images: exerciseImages('Close-Grip_Barbell_Bench_Press') },
    ],
  },
  {
    id: 'back',
    name: 'Back',
    icon: '🔙',
    coverImage: `${IMG_BASE}/Pullups/0.jpg`,
    exercises: [
      { name: 'Pull-Ups', sets: 4, reps: '6-10', description: 'Hang from a bar and pull yourself up until your chin clears it.', images: exerciseImages('Pullups') },
      { name: 'Barbell Row', sets: 4, reps: '8-10', description: 'Bend over and row a barbell toward your lower chest.', images: exerciseImages('Bent_Over_Barbell_Row') },
      { name: 'Lat Pulldown', sets: 3, reps: '10-12', description: 'Pull a wide bar down to your chest on a cable machine.', images: exerciseImages('Wide-Grip_Lat_Pulldown') },
      { name: 'Seated Cable Row', sets: 3, reps: '10-12', description: 'Pull a cable handle toward your midsection while seated.', images: exerciseImages('Seated_Cable_Rows') },
      { name: 'T-Bar Row', sets: 3, reps: '8-10', description: 'Row a loaded T-bar toward your chest while bent over.', images: exerciseImages('T-Bar_Row_with_Handle') },
      { name: 'Face Pull', sets: 3, reps: '12-15', description: 'Pull a rope cable toward your face to target upper back and rear delts.', images: exerciseImages('Face_Pull') },
      { name: 'Assisted Pull Up', sets: 3, reps: '8-10', description: 'Perform pull-ups with machine or band assistance; decrease assistance as you get stronger.', images: exerciseImages('Band_Assisted_Pull-Up') },
      { name: 'Cable V-Bar Seated Row', sets: 3, reps: '10-12', description: 'Pull a V-bar attachment toward your midsection while seated on a cable row.', images: exerciseImages('Seated_Cable_Rows') },
      { name: 'Cable Lat Pulldown', sets: 3, reps: '10-12', description: 'Pull a cable bar down to your upper chest targeting the lats.', images: exerciseImages('Close-Grip_Front_Lat_Pulldown') },
      { name: 'Cable Palm Rotational Row', sets: 3, reps: '10-12', description: 'Row a cable handle while rotating your palm during the pull.', images: exerciseImages('Seated_Cable_Rows') },
      { name: 'V-Bar Pulldown', sets: 3, reps: '10-12', description: 'Pull a V-bar attachment down to your chest on a lat pulldown machine.', images: exerciseImages('V-Bar_Pulldown') },
      { name: 'Lat Pulldown Cable', sets: 3, reps: '10-12', description: 'Pull a wide bar down from a high cable pulley.', images: exerciseImages('Wide-Grip_Lat_Pulldown') },
      { name: 'Dumbbell Pullover', sets: 3, reps: '10-12', description: 'Lie on a bench and lower a dumbbell behind your head in an arc.', images: exerciseImages('Bent-Arm_Dumbbell_Pullover') },
      { name: 'Dumbbell Bent-Over Row', sets: 3, reps: '10-12', description: 'Bend over and row dumbbells toward your waist.', images: exerciseImages('Bent_Over_Two-Dumbbell_Row') },
      { name: 'Dumbbell Bent-Over Reverse Row', sets: 3, reps: '10-12', description: 'Bent-over dumbbell row with palms facing away from you.', images: exerciseImages('Bent_Over_Two-Dumbbell_Row_With_Palms_In') },
      { name: 'Dumbbell Palm Rotational Bent-Over Row', sets: 3, reps: '10-12', description: 'Bent-over row with palm rotation during the pulling movement.', images: exerciseImages('Bent_Over_Two-Dumbbell_Row_With_Palms_In') },
      { name: 'Kettlebell Two Arm Row', sets: 3, reps: '8-10', description: 'Bent over, row two kettlebells toward your waist simultaneously.', images: exerciseImages('Alternating_Kettlebell_Row') },
    ],
  },
  {
    id: 'quadriceps',
    name: 'Quadriceps',
    icon: '🦵',
    coverImage: `${IMG_BASE}/Barbell_Squat/0.jpg`,
    exercises: [
      { name: 'Barbell Squat', sets: 4, reps: '6-10', description: 'Place barbell on upper back, squat down and drive up.', images: exerciseImages('Barbell_Squat') },
      { name: 'Leg Press', sets: 4, reps: '10-12', description: 'Push a weighted platform away using your legs.', images: exerciseImages('Leg_Press') },
      { name: 'Walking Lunges', sets: 3, reps: '12 each leg', description: 'Step forward into a lunge, alternate legs while walking.', images: exerciseImages('Bodyweight_Walking_Lunge') },
      { name: 'Bulgarian Split Squat', sets: 3, reps: '10 each leg', description: 'Squat on one leg with rear foot elevated on a bench.', images: exerciseImages('Split_Squats') },
      { name: 'Leg Extension', sets: 3, reps: '12-15', description: 'Extend your legs on a machine to target the quadriceps.', images: exerciseImages('Leg_Extensions') },
      { name: 'Goblet Squat', sets: 3, reps: '12-15', description: 'Hold a dumbbell at chest level and squat down.', images: exerciseImages('Goblet_Squat') },
      { name: 'Barbell Sumo Squat', sets: 3, reps: '8-10', description: 'Squat with a wide stance holding a barbell on your back.', images: exerciseImages('Barbell_Full_Squat') },
      { name: 'Barbell Overhead Squat', sets: 3, reps: '8-10', description: 'Squat while holding a barbell locked out overhead.', images: exerciseImages('Overhead_Squat') },
      { name: 'Dumbbell Squat', sets: 3, reps: '10-12', description: 'Hold dumbbells at your sides and squat down.', images: exerciseImages('Dumbbell_Squat') },
      { name: 'Dumbbell Lunges', sets: 3, reps: '10 each leg', description: 'Step forward into a lunge while holding dumbbells.', images: exerciseImages('Dumbbell_Lunges') },
      { name: 'Dumbbell Plié Squat', sets: 3, reps: '10-12', description: 'Hold a dumbbell between your legs and squat with a wide stance and toes out.', images: exerciseImages('Dumbbell_Squat') },
      { name: 'Dumbbell Rear Lunge', sets: 3, reps: '10 each leg', description: 'Step backward into a lunge while holding dumbbells.', images: exerciseImages('Dumbbell_Rear_Lunge') },
      { name: 'Leg Press (Old)', sets: 3, reps: '10-12', description: 'Push a weighted platform on the original leg press machine.', images: exerciseImages('Leg_Press') },
      { name: 'Leg Press H', sets: 3, reps: '10-12', description: 'Push a weighted platform on the horizontal leg press machine.', images: exerciseImages('Leg_Press') },
      { name: 'Leg Press (New)', sets: 3, reps: '10-12', description: 'Push a weighted platform on the newer leg press machine.', images: exerciseImages('Leg_Press') },
    ],
  },
  {
    id: 'hamstrings',
    name: 'Hamstrings',
    icon: '🦿',
    coverImage: `${IMG_BASE}/Romanian_Deadlift/0.jpg`,
    exercises: [
      { name: 'Romanian Deadlift', sets: 4, reps: '8-10', description: 'Hinge at the hips with a barbell, keeping legs slightly bent.', images: exerciseImages('Romanian_Deadlift') },
      { name: 'Leg Curl', sets: 3, reps: '10-12', description: 'Curl your legs on a machine to target the hamstrings.', images: exerciseImages('Seated_Leg_Curl') },
      { name: 'Good Mornings', sets: 3, reps: '10-12', description: 'With a barbell on your back, hinge forward at the hips.', images: exerciseImages('Good_Morning') },
      { name: 'Glute-Ham Raise', sets: 3, reps: '8-10', description: 'On a GHD bench, lower your torso and curl back up.', images: exerciseImages('Glute_Ham_Raise') },
      { name: 'Nordic Hamstring Curl', sets: 3, reps: '6-8', description: 'Kneel and slowly lower your body forward, then curl back up.', images: exerciseImages('Natural_Glute_Ham_Raise') },
    ],
  },
  {
    id: 'forearms',
    name: 'Forearms',
    icon: '🤜',
    coverImage: `${IMG_BASE}/Farmers_Walk/0.jpg`,
    exercises: [
      { name: 'Wrist Curl', sets: 3, reps: '15-20', description: 'Rest forearms on a bench and curl a barbell with your wrists.', images: exerciseImages('Palms-Up_Barbell_Wrist_Curl_Over_A_Bench') },
      { name: 'Reverse Wrist Curl', sets: 3, reps: '15-20', description: 'Same as wrist curl but with palms facing down.', images: exerciseImages('Palms-Down_Wrist_Curl_Over_A_Bench') },
      { name: "Farmer's Carry", sets: 3, reps: '40-60 sec', description: 'Walk while holding heavy dumbbells at your sides.', images: exerciseImages('Farmers_Walk') },
      { name: 'Plate Pinch Hold', sets: 3, reps: '20-30 sec', description: 'Pinch two weight plates together and hold.', images: exerciseImages('Plate_Pinch') },
      { name: 'Barbell Standing Wrist Curl', sets: 3, reps: '12-15', description: 'Stand and curl a barbell using only your wrists.', images: exerciseImages('Palms-Up_Barbell_Wrist_Curl_Over_A_Bench') },
    ],
  },
  {
    id: 'chest',
    name: 'Chest',
    icon: '🫁',
    coverImage: `${IMG_BASE}/Barbell_Bench_Press_-_Medium_Grip/0.jpg`,
    exercises: [
      { name: 'Flat Bench Press', sets: 4, reps: '6-10', description: 'Lie on a flat bench and press a barbell upward.', images: exerciseImages('Barbell_Bench_Press_-_Medium_Grip') },
      { name: 'Incline Dumbbell Press', sets: 3, reps: '8-12', description: 'Press dumbbells on an incline bench to target upper chest.', images: exerciseImages('Incline_Dumbbell_Press') },
      { name: 'Chest Fly', sets: 3, reps: '10-12', description: 'Open and close your arms with dumbbells in an arc motion.', images: exerciseImages('Dumbbell_Flyes') },
      { name: 'Push-Up', sets: 3, reps: '15-20', description: 'Lower and push your body up from the floor.', images: exerciseImages('Pushups') },
      { name: 'Pec Deck Machine', sets: 3, reps: '12-15', description: 'Bring the pads together on a machine to squeeze your chest.', images: exerciseImages('Butterfly') },
      { name: 'Decline Bench Press', sets: 3, reps: '8-10', description: 'Press a barbell on a decline bench to target lower chest.', images: exerciseImages('Decline_Barbell_Bench_Press') },
      { name: 'Barbell Chest Press', sets: 3, reps: '8-10', description: 'Lie flat on a bench and press a barbell upward from chest level.', images: exerciseImages('Barbell_Bench_Press_-_Medium_Grip') },
      { name: 'Barbell Chest Press Incline', sets: 3, reps: '8-10', description: 'Press a barbell on an incline bench to target upper chest.', images: exerciseImages('Barbell_Incline_Bench_Press_-_Medium_Grip') },
      { name: 'Chest Press with Support', sets: 3, reps: '10-12', description: 'Press on a chest press machine with back support.', images: exerciseImages('Leverage_Chest_Press') },
      { name: 'Seated Chest Press / Incline', sets: 3, reps: '10-12', description: 'Press on an incline machine chest press from a seated position.', images: exerciseImages('Leverage_Incline_Chest_Press') },
      { name: 'Machine Chest Press', sets: 3, reps: '10-12', description: 'Press forward on a plate-loaded or selectorized chest press machine.', images: exerciseImages('Machine_Bench_Press') },
      { name: 'Pec Fly', sets: 3, reps: '10-12', description: 'Bring handles together on a pec fly machine to squeeze your chest.', images: exerciseImages('Butterfly') },
      { name: 'Dumbbell Larsen Press', sets: 3, reps: '8-10', description: 'Press dumbbells on a flat bench with legs straight and elevated off the floor.', images: exerciseImages('Dumbbell_Bench_Press') },
      { name: 'Dumbbell Close-Grip Press', sets: 3, reps: '10-12', description: 'Press dumbbells with a narrow grip to target inner chest and triceps.', images: exerciseImages('Close-Grip_Dumbbell_Press') },
      { name: 'Dumbbell Incline Bench Press', sets: 3, reps: '8-10', description: 'Press dumbbells on an incline bench for upper chest.', images: exerciseImages('Incline_Dumbbell_Press') },
      { name: 'Dumbbell Bench Press', sets: 3, reps: '8-10', description: 'Press dumbbells upward while lying on a flat bench.', images: exerciseImages('Dumbbell_Bench_Press') },
      { name: 'Dumbbell Arnold Bench Press', sets: 3, reps: '8-10', description: 'Bench press with dumbbells using an Arnold rotation during the press.', images: exerciseImages('Dumbbell_Bench_Press_with_Neutral_Grip') },
      { name: 'Floor Dumbbell Fly', sets: 3, reps: '10-12', description: 'Lie on the floor and perform dumbbell flyes with a limited range of motion.', images: exerciseImages('Dumbbell_Flyes') },
      { name: 'Dumbbell One Arm Floor Fly', sets: 3, reps: '10 each arm', description: 'Lie on the floor and perform a single-arm dumbbell fly.', images: exerciseImages('One-Arm_Flat_Bench_Dumbbell_Flye') },
      { name: 'Dumbbell One Arm Wide Grip Bench Press', sets: 3, reps: '8-10', description: 'Single-arm bench press with a wide elbow position.', images: exerciseImages('Dumbbell_Floor_Press') },
      { name: 'Smith Incline Bench Press', sets: 3, reps: '8-10', description: 'Incline bench press using the Smith machine for guided movement.', images: exerciseImages('Smith_Machine_Incline_Bench_Press') },
    ],
  },
  {
    id: 'biceps',
    name: 'Biceps',
    icon: '💪',
    coverImage: `${IMG_BASE}/Barbell_Curl/0.jpg`,
    exercises: [
      { name: 'Barbell Curl', sets: 4, reps: '8-12', description: 'Curl a barbell toward your shoulders while standing.', images: exerciseImages('Barbell_Curl') },
      { name: 'Hammer Curl', sets: 3, reps: '10-12', description: 'Curl dumbbells with a neutral grip to target the brachialis.', images: exerciseImages('Hammer_Curls') },
      { name: 'Preacher Curl', sets: 3, reps: '10-12', description: 'Curl on a preacher bench for isolated bicep contraction.', images: exerciseImages('Preacher_Curl') },
      { name: 'Concentration Curl', sets: 3, reps: '10-12', description: 'Sit and curl a dumbbell with your elbow braced on your thigh.', images: exerciseImages('Concentration_Curls') },
      { name: 'Cable Curl', sets: 3, reps: '12-15', description: 'Curl a cable bar from a low pulley position.', images: exerciseImages('Standing_Biceps_Cable_Curl') },
      { name: 'Chin-Up', sets: 3, reps: '6-10', description: 'Pull yourself up on a bar with an underhand grip.', images: exerciseImages('Chin-Up') },
      { name: 'Barbell Prone Incline Curl', sets: 3, reps: '8-10', description: 'Lie face down on an incline bench and curl a barbell.', images: exerciseImages('Barbell_Curls_Lying_Against_An_Incline') },
      { name: 'Barbell Preacher Curl', sets: 3, reps: '10-12', description: 'Curl a barbell on a preacher bench for strict bicep isolation.', images: exerciseImages('Preacher_Curl') },
      { name: 'Cable Bicep Curl', sets: 3, reps: '10-12', description: 'Curl a handle attached to a low cable pulley.', images: exerciseImages('Standing_Biceps_Cable_Curl') },
      { name: 'Dumbbell Inner Bicep Curl', sets: 3, reps: '10-12', description: 'Curl dumbbells with elbows out wide to target the inner bicep head.', images: exerciseImages('Incline_Inner_Biceps_Curl') },
      { name: 'Dumbbell Bicep Curl', sets: 3, reps: '10-12', description: 'Standard standing dumbbell curl alternating or both arms.', images: exerciseImages('Dumbbell_Bicep_Curl') },
      { name: 'Dumbbell Reverse Preacher Curl', sets: 3, reps: '10-12', description: 'Curl dumbbells on a preacher bench with palms facing down.', images: exerciseImages('Dumbbell_Prone_Incline_Curl') },
      { name: 'Dumbbell Hammer Strict Curl', sets: 3, reps: '10-12', description: 'Strict hammer curl keeping upper arms pinned to your sides.', images: exerciseImages('Hammer_Curls') },
      { name: 'Dumbbell Seat Drag Curl', sets: 3, reps: '10-12', description: 'Seated drag curl pulling dumbbells up along your torso.', images: exerciseImages('Drag_Curl') },
      { name: 'Dumbbell Seated Double Concentrated', sets: 3, reps: '10-12', description: 'Seated concentration curl using both arms simultaneously.', images: exerciseImages('Seated_Dumbbell_Inner_Biceps_Curl') },
      { name: 'Barbell Close Grip Preacher', sets: 3, reps: '10-12', description: 'Preacher curl with a close grip on the barbell.', images: exerciseImages('Close-Grip_Standing_Barbell_Curl') },
      { name: 'Dumbbell Concentration Curl', sets: 3, reps: '10-12', description: 'Seated curl with elbow braced on inner thigh for strict isolation.', images: exerciseImages('Concentration_Curls') },
    ],
  },
  {
    id: 'shoulders',
    name: 'Shoulders',
    icon: '🙌',
    coverImage: `${IMG_BASE}/Standing_Military_Press/0.jpg`,
    exercises: [
      { name: 'Overhead Press', sets: 4, reps: '6-10', description: 'Press a barbell or dumbbells overhead while standing.', images: exerciseImages('Standing_Military_Press') },
      { name: 'Lateral Raise', sets: 3, reps: '12-15', description: 'Raise dumbbells to your sides up to shoulder level.', images: exerciseImages('Side_Lateral_Raise') },
      { name: 'Front Raise', sets: 3, reps: '12-15', description: 'Raise dumbbells in front of you to shoulder level.', images: exerciseImages('Front_Dumbbell_Raise') },
      { name: 'Rear Delt Fly', sets: 3, reps: '12-15', description: 'Bend forward and raise dumbbells to your sides.', images: exerciseImages('Seated_Bent-Over_Rear_Delt_Raise') },
      { name: 'Arnold Press', sets: 3, reps: '8-10', description: 'Rotate dumbbells from front to side while pressing overhead.', images: exerciseImages('Arnold_Dumbbell_Press') },
      { name: 'Barbell Behind the Back', sets: 3, reps: '10-12', description: 'Hold a barbell behind your back and raise or press it.', images: exerciseImages('Barbell_Shrug_Behind_The_Back') },
      { name: 'Barbell Push Press', sets: 3, reps: '6-8', description: 'Use a slight leg drive to press a barbell overhead.', images: exerciseImages('Barbell_Shoulder_Press') },
      { name: 'Shoulder Press', sets: 3, reps: '8-10', description: 'Press weight overhead from shoulder level on a machine or with dumbbells.', images: exerciseImages('Barbell_Shoulder_Press') },
      { name: 'Dumbbell Seated Lateral Raise', sets: 3, reps: '12-15', description: 'Seated lateral raise lifting dumbbells out to your sides.', images: exerciseImages('Seated_Side_Lateral_Raise') },
      { name: 'Dumbbell Incline Y Raise', sets: 3, reps: '10-12', description: 'Lie face down on an incline bench and raise dumbbells in a Y shape.', images: exerciseImages('Dumbbell_Incline_Shoulder_Raise') },
      { name: 'Rear Lateral Raise', sets: 3, reps: '12-15', description: 'Bend forward and raise dumbbells to your sides targeting rear delts.', images: exerciseImages('Dumbbell_Lying_Rear_Lateral_Raise') },
      { name: 'Dumbbell Front Raise', sets: 3, reps: '12-15', description: 'Raise dumbbells in front of you to shoulder level, alternating or together.', images: exerciseImages('Front_Dumbbell_Raise') },
      { name: 'Seated Dumbbell Shoulder Press', sets: 3, reps: '8-10', description: 'Seated overhead press with dumbbells.', images: exerciseImages('Dumbbell_Shoulder_Press') },
      { name: 'Seated Dumbbell Front Raise Alt', sets: 3, reps: '10-12', description: 'Seated alternating front raise with dumbbells.', images: exerciseImages('Front_Dumbbell_Raise') },
      { name: 'Cable Upright Row', sets: 3, reps: '10-12', description: 'Pull a cable bar upward to chin level, elbows leading.', images: exerciseImages('Upright_Barbell_Row') },
      { name: 'Kettlebell Seesaw Press', sets: 3, reps: '8-10', description: 'Alternating overhead press with kettlebells in a seesaw motion.', images: exerciseImages('Kettlebell_Seesaw_Press') },
      { name: 'Kettlebell Windmill', sets: 3, reps: '8-10 each side', description: 'Hold a kettlebell overhead and bend sideways touching the floor.', images: exerciseImages('Kettlebell_Windmill') },
      { name: 'Dumbbell Low Windmill', sets: 3, reps: '8-10 each side', description: 'Hold a dumbbell low and bend sideways in a windmill motion.', images: exerciseImages('Kettlebell_Windmill') },
      { name: 'Kettlebell Lateral Raise', sets: 3, reps: '10-12', description: 'Raise kettlebells to your sides up to shoulder level.', images: exerciseImages('Side_Lateral_Raise') },
      { name: 'Incline Bench Rear Fly', sets: 3, reps: '12-15', description: 'Lie face down on an incline bench and raise dumbbells to your sides.', images: exerciseImages('Seated_Bent-Over_Rear_Delt_Raise') },
      { name: 'Dumbbell Arnold Press', sets: 3, reps: '8-10', description: 'Rotate dumbbells from front to side while pressing overhead.', images: exerciseImages('Arnold_Dumbbell_Press') },
    ],
  },
  {
    id: 'lower-back',
    name: 'Lower Back',
    icon: '🔻',
    coverImage: `${IMG_BASE}/Hyperextensions_Back_Extensions/0.jpg`,
    exercises: [
      { name: 'Back Extension', sets: 3, reps: '12-15', description: 'On a Roman chair, lower and raise your torso.', images: exerciseImages('Hyperextensions_Back_Extensions') },
      { name: 'Romanian Deadlift', sets: 4, reps: '8-10', description: 'Hinge at the hips with a barbell, keeping legs slightly bent.', images: exerciseImages('Romanian_Deadlift') },
      { name: 'Good Morning', sets: 3, reps: '10-12', description: 'With a barbell on your back, hinge forward at the hips.', images: exerciseImages('Good_Morning') },
      { name: 'Superman', sets: 3, reps: '12-15', description: 'Lie face down and raise your arms and legs off the ground.', images: exerciseImages('Superman') },
      { name: 'Hyperextension 45deg', sets: 3, reps: '10-12', description: 'Perform back extensions on a 45-degree hyperextension bench.', images: exerciseImages('Hyperextensions_Back_Extensions') },
      { name: 'Weighted Hyperextension', sets: 3, reps: '8-10', description: 'Hold a weight plate and perform hyperextensions for added resistance.', images: exerciseImages('Weighted_Ball_Hyperextension') },
    ],
  },
  {
    id: 'glutes',
    name: 'Glutes',
    icon: '🍑',
    coverImage: `${IMG_BASE}/Barbell_Hip_Thrust/0.jpg`,
    exercises: [
      { name: 'Hip Thrust', sets: 4, reps: '8-12', description: 'Sit against a bench and thrust a barbell upward with your hips.', images: exerciseImages('Barbell_Hip_Thrust') },
      { name: 'Glute Bridge', sets: 3, reps: '12-15', description: 'Lie on your back and raise your hips with a barbell.', images: exerciseImages('Barbell_Glute_Bridge') },
      { name: 'Step-Ups', sets: 3, reps: '10 each leg', description: 'Step onto a box or bench holding dumbbells.', images: exerciseImages('Barbell_Step_Ups') },
      { name: 'Cable Kickbacks', sets: 3, reps: '12 each leg', description: 'Kick your leg back against cable resistance.', images: exerciseImages('One-Legged_Cable_Kickback') },
      { name: 'Bulgarian Split Squat', sets: 3, reps: '10 each leg', description: 'Squat on one leg with rear foot elevated on a bench.', images: exerciseImages('Split_Squats') },
    ],
  },
  {
    id: 'calves',
    name: 'Calves',
    icon: '🦶',
    coverImage: `${IMG_BASE}/Standing_Calf_Raises/0.jpg`,
    exercises: [
      { name: 'Standing Calf Raise', sets: 4, reps: '12-15', description: 'Stand on a platform and raise your heels upward.', images: exerciseImages('Standing_Calf_Raises') },
      { name: 'Seated Calf Raise', sets: 3, reps: '15-20', description: 'Raise your heels while seated with weight on your knees.', images: exerciseImages('Seated_Calf_Raise') },
      { name: 'Donkey Calf Raise', sets: 3, reps: '12-15', description: 'Bend at the waist and raise your heels with weight on your back.', images: exerciseImages('Donkey_Calf_Raises') },
      { name: "Farmer's Walk on Toes", sets: 3, reps: '30-40 sec', description: 'Walk on your toes while holding heavy dumbbells.', images: exerciseImages('Farmers_Walk') },
      { name: 'Calf Horizontal', sets: 3, reps: '15-20', description: 'Calf raise on the leg press machine pushing the platform with your toes.', images: exerciseImages('Calf_Press_On_The_Leg_Press_Machine') },
      { name: 'Seated Calf Raise New', sets: 3, reps: '15-20', description: 'Seated calf raise on the newer machine with additional base weight.', images: exerciseImages('Barbell_Seated_Calf_Raise') },
      { name: 'Elevated Standing Calf Raise', sets: 3, reps: '12-15', description: 'Stand on an elevated surface and raise your heels for full range of motion.', images: exerciseImages('Standing_Calf_Raises') },
      { name: 'Weighted Elevated Standing Calf', sets: 3, reps: '10-12', description: 'Elevated calf raise holding dumbbells for added resistance.', images: exerciseImages('Standing_Calf_Raises') },
    ],
  },
  {
    id: 'trapezius',
    name: 'Trapezius',
    icon: '🔺',
    coverImage: `${IMG_BASE}/Barbell_Shrug/0.jpg`,
    exercises: [
      { name: 'Barbell Shrug', sets: 4, reps: '10-15', description: 'Shrug your shoulders upward while holding a barbell.', images: exerciseImages('Barbell_Shrug') },
      { name: 'Dumbbell Shrug', sets: 3, reps: '12-15', description: 'Shrug your shoulders while holding dumbbells at your sides.', images: exerciseImages('Dumbbell_Shrug') },
      { name: 'Upright Row', sets: 3, reps: '10-12', description: 'Pull a barbell up along your body to chin level.', images: exerciseImages('Upright_Barbell_Row') },
      { name: 'Face Pull', sets: 3, reps: '12-15', description: 'Pull a rope cable toward your face to target upper traps.', images: exerciseImages('Face_Pull') },
      { name: "Farmer's Carry", sets: 3, reps: '40-60 sec', description: 'Walk while holding heavy dumbbells at your sides.', images: exerciseImages('Farmers_Walk') },
      { name: 'Low Cable Shrug', sets: 3, reps: '12-15', description: 'Shrug your shoulders using a low cable pulley.', images: exerciseImages('Cable_Shrugs') },
      { name: 'Smith Bar Shrug', sets: 3, reps: '10-12', description: 'Shrug your shoulders using the Smith machine barbell.', images: exerciseImages('Smith_Machine_Behind_the_Back_Shrug') },
      { name: 'Smith Back Shrug', sets: 3, reps: '10-12', description: 'Shrug with the Smith machine bar behind your back.', images: exerciseImages('Smith_Machine_Behind_the_Back_Shrug') },
      { name: 'Dumbbell Incline Shrug', sets: 3, reps: '12-15', description: 'Lie face down on an incline bench and shrug dumbbells upward.', images: exerciseImages('Dumbbell_Shrug') },
    ],
  },
];
